# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.10

# Default target executed when no arguments are given to make.
default_target: all

.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:


#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:


# Remove some rules from gmake that .SUFFIXES does not remove.
SUFFIXES =

.SUFFIXES: .hpux_make_needs_suffix_list


# Suppress display of executed commands.
$(VERBOSE).SILENT:


# A target that is always out of date.
cmake_force:

.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /home/arthur/.jetBrains/clion-2017.3.1/bin/cmake/bin/cmake

# The command to remove a file.
RM = /home/arthur/.jetBrains/clion-2017.3.1/bin/cmake/bin/cmake -E remove -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/arthur/delivery/TEK2/CPP/cpp_indie_studio

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/arthur/delivery/TEK2/CPP/cpp_indie_studio

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/home/arthur/.jetBrains/clion-2017.3.1/bin/cmake/bin/cmake -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache

.PHONY : rebuild_cache/fast

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "No interactive CMake dialog available..."
	/home/arthur/.jetBrains/clion-2017.3.1/bin/cmake/bin/cmake -E echo No\ interactive\ CMake\ dialog\ available.
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache

.PHONY : edit_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/arthur/delivery/TEK2/CPP/cpp_indie_studio/CMakeFiles /home/arthur/delivery/TEK2/CPP/cpp_indie_studio/CMakeFiles/progress.marks
	$(MAKE) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/arthur/delivery/TEK2/CPP/cpp_indie_studio/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean

.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named bomberman

# Build rule for target.
bomberman: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 bomberman
.PHONY : bomberman

# fast build rule for target.
bomberman/fast:
	$(MAKE) -f CMakeFiles/bomberman.dir/build.make CMakeFiles/bomberman.dir/build
.PHONY : bomberman/fast

src/Abstracts/ABombDropper.o: src/Abstracts/ABombDropper.cpp.o

.PHONY : src/Abstracts/ABombDropper.o

# target to build an object file
src/Abstracts/ABombDropper.cpp.o:
	$(MAKE) -f CMakeFiles/bomberman.dir/build.make CMakeFiles/bomberman.dir/src/Abstracts/ABombDropper.cpp.o
.PHONY : src/Abstracts/ABombDropper.cpp.o

src/Abstracts/ABombDropper.i: src/Abstracts/ABombDropper.cpp.i

.PHONY : src/Abstracts/ABombDropper.i

# target to preprocess a source file
src/Abstracts/ABombDropper.cpp.i:
	$(MAKE) -f CMakeFiles/bomberman.dir/build.make CMakeFiles/bomberman.dir/src/Abstracts/ABombDropper.cpp.i
.PHONY : src/Abstracts/ABombDropper.cpp.i

src/Abstracts/ABombDropper.s: src/Abstracts/ABombDropper.cpp.s

.PHONY : src/Abstracts/ABombDropper.s

# target to generate assembly for a file
src/Abstracts/ABombDropper.cpp.s:
	$(MAKE) -f CMakeFiles/bomberman.dir/build.make CMakeFiles/bomberman.dir/src/Abstracts/ABombDropper.cpp.s
.PHONY : src/Abstracts/ABombDropper.cpp.s

src/Abstracts/AMenuSound.o: src/Abstracts/AMenuSound.cpp.o

.PHONY : src/Abstracts/AMenuSound.o

# target to build an object file
src/Abstracts/AMenuSound.cpp.o:
	$(MAKE) -f CMakeFiles/bomberman.dir/build.make CMakeFiles/bomberman.dir/src/Abstracts/AMenuSound.cpp.o
.PHONY : src/Abstracts/AMenuSound.cpp.o

src/Abstracts/AMenuSound.i: src/Abstracts/AMenuSound.cpp.i

.PHONY : src/Abstracts/AMenuSound.i

# target to preprocess a source file
src/Abstracts/AMenuSound.cpp.i:
	$(MAKE) -f CMakeFiles/bomberman.dir/build.make CMakeFiles/bomberman.dir/src/Abstracts/AMenuSound.cpp.i
.PHONY : src/Abstracts/AMenuSound.cpp.i

src/Abstracts/AMenuSound.s: src/Abstracts/AMenuSound.cpp.s

.PHONY : src/Abstracts/AMenuSound.s

# target to generate assembly for a file
src/Abstracts/AMenuSound.cpp.s:
	$(MAKE) -f CMakeFiles/bomberman.dir/build.make CMakeFiles/bomberman.dir/src/Abstracts/AMenuSound.cpp.s
.PHONY : src/Abstracts/AMenuSound.cpp.s

src/Abstracts/AState.o: src/Abstracts/AState.cpp.o

.PHONY : src/Abstracts/AState.o

# target to build an object file
src/Abstracts/AState.cpp.o:
	$(MAKE) -f CMakeFiles/bomberman.dir/build.make CMakeFiles/bomberman.dir/src/Abstracts/AState.cpp.o
.PHONY : src/Abstracts/AState.cpp.o

src/Abstracts/AState.i: src/Abstracts/AState.cpp.i

.PHONY : src/Abstracts/AState.i

# target to preprocess a source file
src/Abstracts/AState.cpp.i:
	$(MAKE) -f CMakeFiles/bomberman.dir/build.make CMakeFiles/bomberman.dir/src/Abstracts/AState.cpp.i
.PHONY : src/Abstracts/AState.cpp.i

src/Abstracts/AState.s: src/Abstracts/AState.cpp.s

.PHONY : src/Abstracts/AState.s

# target to generate assembly for a file
src/Abstracts/AState.cpp.s:
	$(MAKE) -f CMakeFiles/bomberman.dir/build.make CMakeFiles/bomberman.dir/src/Abstracts/AState.cpp.s
.PHONY : src/Abstracts/AState.cpp.s

src/Abstracts/AStateShare.o: src/Abstracts/AStateShare.cpp.o

.PHONY : src/Abstracts/AStateShare.o

# target to build an object file
src/Abstracts/AStateShare.cpp.o:
	$(MAKE) -f CMakeFiles/bomberman.dir/build.make CMakeFiles/bomberman.dir/src/Abstracts/AStateShare.cpp.o
.PHONY : src/Abstracts/AStateShare.cpp.o

src/Abstracts/AStateShare.i: src/Abstracts/AStateShare.cpp.i

.PHONY : src/Abstracts/AStateShare.i

# target to preprocess a source file
src/Abstracts/AStateShare.cpp.i:
	$(MAKE) -f CMakeFiles/bomberman.dir/build.make CMakeFiles/bomberman.dir/src/Abstracts/AStateShare.cpp.i
.PHONY : src/Abstracts/AStateShare.cpp.i

src/Abstracts/AStateShare.s: src/Abstracts/AStateShare.cpp.s

.PHONY : src/Abstracts/AStateShare.s

# target to generate assembly for a file
src/Abstracts/AStateShare.cpp.s:
	$(MAKE) -f CMakeFiles/bomberman.dir/build.make CMakeFiles/bomberman.dir/src/Abstracts/AStateShare.cpp.s
.PHONY : src/Abstracts/AStateShare.cpp.s

src/Game/AController.o: src/Game/AController.cpp.o

.PHONY : src/Game/AController.o

# target to build an object file
src/Game/AController.cpp.o:
	$(MAKE) -f CMakeFiles/bomberman.dir/build.make CMakeFiles/bomberman.dir/src/Game/AController.cpp.o
.PHONY : src/Game/AController.cpp.o

src/Game/AController.i: src/Game/AController.cpp.i

.PHONY : src/Game/AController.i

# target to preprocess a source file
src/Game/AController.cpp.i:
	$(MAKE) -f CMakeFiles/bomberman.dir/build.make CMakeFiles/bomberman.dir/src/Game/AController.cpp.i
.PHONY : src/Game/AController.cpp.i

src/Game/AController.s: src/Game/AController.cpp.s

.PHONY : src/Game/AController.s

# target to generate assembly for a file
src/Game/AController.cpp.s:
	$(MAKE) -f CMakeFiles/bomberman.dir/build.make CMakeFiles/bomberman.dir/src/Game/AController.cpp.s
.PHONY : src/Game/AController.cpp.s

src/Game/AEntity.o: src/Game/AEntity.cpp.o

.PHONY : src/Game/AEntity.o

# target to build an object file
src/Game/AEntity.cpp.o:
	$(MAKE) -f CMakeFiles/bomberman.dir/build.make CMakeFiles/bomberman.dir/src/Game/AEntity.cpp.o
.PHONY : src/Game/AEntity.cpp.o

src/Game/AEntity.i: src/Game/AEntity.cpp.i

.PHONY : src/Game/AEntity.i

# target to preprocess a source file
src/Game/AEntity.cpp.i:
	$(MAKE) -f CMakeFiles/bomberman.dir/build.make CMakeFiles/bomberman.dir/src/Game/AEntity.cpp.i
.PHONY : src/Game/AEntity.cpp.i

src/Game/AEntity.s: src/Game/AEntity.cpp.s

.PHONY : src/Game/AEntity.s

# target to generate assembly for a file
src/Game/AEntity.cpp.s:
	$(MAKE) -f CMakeFiles/bomberman.dir/build.make CMakeFiles/bomberman.dir/src/Game/AEntity.cpp.s
.PHONY : src/Game/AEntity.cpp.s

src/Game/BIAController.o: src/Game/BIAController.cpp.o

.PHONY : src/Game/BIAController.o

# target to build an object file
src/Game/BIAController.cpp.o:
	$(MAKE) -f CMakeFiles/bomberman.dir/build.make CMakeFiles/bomberman.dir/src/Game/BIAController.cpp.o
.PHONY : src/Game/BIAController.cpp.o

src/Game/BIAController.i: src/Game/BIAController.cpp.i

.PHONY : src/Game/BIAController.i

# target to preprocess a source file
src/Game/BIAController.cpp.i:
	$(MAKE) -f CMakeFiles/bomberman.dir/build.make CMakeFiles/bomberman.dir/src/Game/BIAController.cpp.i
.PHONY : src/Game/BIAController.cpp.i

src/Game/BIAController.s: src/Game/BIAController.cpp.s

.PHONY : src/Game/BIAController.s

# target to generate assembly for a file
src/Game/BIAController.cpp.s:
	$(MAKE) -f CMakeFiles/bomberman.dir/build.make CMakeFiles/bomberman.dir/src/Game/BIAController.cpp.s
.PHONY : src/Game/BIAController.cpp.s

src/Game/BKeyboardController.o: src/Game/BKeyboardController.cpp.o

.PHONY : src/Game/BKeyboardController.o

# target to build an object file
src/Game/BKeyboardController.cpp.o:
	$(MAKE) -f CMakeFiles/bomberman.dir/build.make CMakeFiles/bomberman.dir/src/Game/BKeyboardController.cpp.o
.PHONY : src/Game/BKeyboardController.cpp.o

src/Game/BKeyboardController.i: src/Game/BKeyboardController.cpp.i

.PHONY : src/Game/BKeyboardController.i

# target to preprocess a source file
src/Game/BKeyboardController.cpp.i:
	$(MAKE) -f CMakeFiles/bomberman.dir/build.make CMakeFiles/bomberman.dir/src/Game/BKeyboardController.cpp.i
.PHONY : src/Game/BKeyboardController.cpp.i

src/Game/BKeyboardController.s: src/Game/BKeyboardController.cpp.s

.PHONY : src/Game/BKeyboardController.s

# target to generate assembly for a file
src/Game/BKeyboardController.cpp.s:
	$(MAKE) -f CMakeFiles/bomberman.dir/build.make CMakeFiles/bomberman.dir/src/Game/BKeyboardController.cpp.s
.PHONY : src/Game/BKeyboardController.cpp.s

src/Game/Controllable.o: src/Game/Controllable.cpp.o

.PHONY : src/Game/Controllable.o

# target to build an object file
src/Game/Controllable.cpp.o:
	$(MAKE) -f CMakeFiles/bomberman.dir/build.make CMakeFiles/bomberman.dir/src/Game/Controllable.cpp.o
.PHONY : src/Game/Controllable.cpp.o

src/Game/Controllable.i: src/Game/Controllable.cpp.i

.PHONY : src/Game/Controllable.i

# target to preprocess a source file
src/Game/Controllable.cpp.i:
	$(MAKE) -f CMakeFiles/bomberman.dir/build.make CMakeFiles/bomberman.dir/src/Game/Controllable.cpp.i
.PHONY : src/Game/Controllable.cpp.i

src/Game/Controllable.s: src/Game/Controllable.cpp.s

.PHONY : src/Game/Controllable.s

# target to generate assembly for a file
src/Game/Controllable.cpp.s:
	$(MAKE) -f CMakeFiles/bomberman.dir/build.make CMakeFiles/bomberman.dir/src/Game/Controllable.cpp.s
.PHONY : src/Game/Controllable.cpp.s

src/Game/Entities/AAnimatedEntity.o: src/Game/Entities/AAnimatedEntity.cpp.o

.PHONY : src/Game/Entities/AAnimatedEntity.o

# target to build an object file
src/Game/Entities/AAnimatedEntity.cpp.o:
	$(MAKE) -f CMakeFiles/bomberman.dir/build.make CMakeFiles/bomberman.dir/src/Game/Entities/AAnimatedEntity.cpp.o
.PHONY : src/Game/Entities/AAnimatedEntity.cpp.o

src/Game/Entities/AAnimatedEntity.i: src/Game/Entities/AAnimatedEntity.cpp.i

.PHONY : src/Game/Entities/AAnimatedEntity.i

# target to preprocess a source file
src/Game/Entities/AAnimatedEntity.cpp.i:
	$(MAKE) -f CMakeFiles/bomberman.dir/build.make CMakeFiles/bomberman.dir/src/Game/Entities/AAnimatedEntity.cpp.i
.PHONY : src/Game/Entities/AAnimatedEntity.cpp.i

src/Game/Entities/AAnimatedEntity.s: src/Game/Entities/AAnimatedEntity.cpp.s

.PHONY : src/Game/Entities/AAnimatedEntity.s

# target to generate assembly for a file
src/Game/Entities/AAnimatedEntity.cpp.s:
	$(MAKE) -f CMakeFiles/bomberman.dir/build.make CMakeFiles/bomberman.dir/src/Game/Entities/AAnimatedEntity.cpp.s
.PHONY : src/Game/Entities/AAnimatedEntity.cpp.s

src/Game/Entities/ABonusEntity.o: src/Game/Entities/ABonusEntity.cpp.o

.PHONY : src/Game/Entities/ABonusEntity.o

# target to build an object file
src/Game/Entities/ABonusEntity.cpp.o:
	$(MAKE) -f CMakeFiles/bomberman.dir/build.make CMakeFiles/bomberman.dir/src/Game/Entities/ABonusEntity.cpp.o
.PHONY : src/Game/Entities/ABonusEntity.cpp.o

src/Game/Entities/ABonusEntity.i: src/Game/Entities/ABonusEntity.cpp.i

.PHONY : src/Game/Entities/ABonusEntity.i

# target to preprocess a source file
src/Game/Entities/ABonusEntity.cpp.i:
	$(MAKE) -f CMakeFiles/bomberman.dir/build.make CMakeFiles/bomberman.dir/src/Game/Entities/ABonusEntity.cpp.i
.PHONY : src/Game/Entities/ABonusEntity.cpp.i

src/Game/Entities/ABonusEntity.s: src/Game/Entities/ABonusEntity.cpp.s

.PHONY : src/Game/Entities/ABonusEntity.s

# target to generate assembly for a file
src/Game/Entities/ABonusEntity.cpp.s:
	$(MAKE) -f CMakeFiles/bomberman.dir/build.make CMakeFiles/bomberman.dir/src/Game/Entities/ABonusEntity.cpp.s
.PHONY : src/Game/Entities/ABonusEntity.cpp.s

src/Game/Entities/BlockEntity.o: src/Game/Entities/BlockEntity.cpp.o

.PHONY : src/Game/Entities/BlockEntity.o

# target to build an object file
src/Game/Entities/BlockEntity.cpp.o:
	$(MAKE) -f CMakeFiles/bomberman.dir/build.make CMakeFiles/bomberman.dir/src/Game/Entities/BlockEntity.cpp.o
.PHONY : src/Game/Entities/BlockEntity.cpp.o

src/Game/Entities/BlockEntity.i: src/Game/Entities/BlockEntity.cpp.i

.PHONY : src/Game/Entities/BlockEntity.i

# target to preprocess a source file
src/Game/Entities/BlockEntity.cpp.i:
	$(MAKE) -f CMakeFiles/bomberman.dir/build.make CMakeFiles/bomberman.dir/src/Game/Entities/BlockEntity.cpp.i
.PHONY : src/Game/Entities/BlockEntity.cpp.i

src/Game/Entities/BlockEntity.s: src/Game/Entities/BlockEntity.cpp.s

.PHONY : src/Game/Entities/BlockEntity.s

# target to generate assembly for a file
src/Game/Entities/BlockEntity.cpp.s:
	$(MAKE) -f CMakeFiles/bomberman.dir/build.make CMakeFiles/bomberman.dir/src/Game/Entities/BlockEntity.cpp.s
.PHONY : src/Game/Entities/BlockEntity.cpp.s

src/Game/Entities/BombEntity.o: src/Game/Entities/BombEntity.cpp.o

.PHONY : src/Game/Entities/BombEntity.o

# target to build an object file
src/Game/Entities/BombEntity.cpp.o:
	$(MAKE) -f CMakeFiles/bomberman.dir/build.make CMakeFiles/bomberman.dir/src/Game/Entities/BombEntity.cpp.o
.PHONY : src/Game/Entities/BombEntity.cpp.o

src/Game/Entities/BombEntity.i: src/Game/Entities/BombEntity.cpp.i

.PHONY : src/Game/Entities/BombEntity.i

# target to preprocess a source file
src/Game/Entities/BombEntity.cpp.i:
	$(MAKE) -f CMakeFiles/bomberman.dir/build.make CMakeFiles/bomberman.dir/src/Game/Entities/BombEntity.cpp.i
.PHONY : src/Game/Entities/BombEntity.cpp.i

src/Game/Entities/BombEntity.s: src/Game/Entities/BombEntity.cpp.s

.PHONY : src/Game/Entities/BombEntity.s

# target to generate assembly for a file
src/Game/Entities/BombEntity.cpp.s:
	$(MAKE) -f CMakeFiles/bomberman.dir/build.make CMakeFiles/bomberman.dir/src/Game/Entities/BombEntity.cpp.s
.PHONY : src/Game/Entities/BombEntity.cpp.s

src/Game/Entities/Bonus/InvertBonus.o: src/Game/Entities/Bonus/InvertBonus.cpp.o

.PHONY : src/Game/Entities/Bonus/InvertBonus.o

# target to build an object file
src/Game/Entities/Bonus/InvertBonus.cpp.o:
	$(MAKE) -f CMakeFiles/bomberman.dir/build.make CMakeFiles/bomberman.dir/src/Game/Entities/Bonus/InvertBonus.cpp.o
.PHONY : src/Game/Entities/Bonus/InvertBonus.cpp.o

src/Game/Entities/Bonus/InvertBonus.i: src/Game/Entities/Bonus/InvertBonus.cpp.i

.PHONY : src/Game/Entities/Bonus/InvertBonus.i

# target to preprocess a source file
src/Game/Entities/Bonus/InvertBonus.cpp.i:
	$(MAKE) -f CMakeFiles/bomberman.dir/build.make CMakeFiles/bomberman.dir/src/Game/Entities/Bonus/InvertBonus.cpp.i
.PHONY : src/Game/Entities/Bonus/InvertBonus.cpp.i

src/Game/Entities/Bonus/InvertBonus.s: src/Game/Entities/Bonus/InvertBonus.cpp.s

.PHONY : src/Game/Entities/Bonus/InvertBonus.s

# target to generate assembly for a file
src/Game/Entities/Bonus/InvertBonus.cpp.s:
	$(MAKE) -f CMakeFiles/bomberman.dir/build.make CMakeFiles/bomberman.dir/src/Game/Entities/Bonus/InvertBonus.cpp.s
.PHONY : src/Game/Entities/Bonus/InvertBonus.cpp.s

src/Game/Entities/Bonus/ResetFireRangeBonus.o: src/Game/Entities/Bonus/ResetFireRangeBonus.cpp.o

.PHONY : src/Game/Entities/Bonus/ResetFireRangeBonus.o

# target to build an object file
src/Game/Entities/Bonus/ResetFireRangeBonus.cpp.o:
	$(MAKE) -f CMakeFiles/bomberman.dir/build.make CMakeFiles/bomberman.dir/src/Game/Entities/Bonus/ResetFireRangeBonus.cpp.o
.PHONY : src/Game/Entities/Bonus/ResetFireRangeBonus.cpp.o

src/Game/Entities/Bonus/ResetFireRangeBonus.i: src/Game/Entities/Bonus/ResetFireRangeBonus.cpp.i

.PHONY : src/Game/Entities/Bonus/ResetFireRangeBonus.i

# target to preprocess a source file
src/Game/Entities/Bonus/ResetFireRangeBonus.cpp.i:
	$(MAKE) -f CMakeFiles/bomberman.dir/build.make CMakeFiles/bomberman.dir/src/Game/Entities/Bonus/ResetFireRangeBonus.cpp.i
.PHONY : src/Game/Entities/Bonus/ResetFireRangeBonus.cpp.i

src/Game/Entities/Bonus/ResetFireRangeBonus.s: src/Game/Entities/Bonus/ResetFireRangeBonus.cpp.s

.PHONY : src/Game/Entities/Bonus/ResetFireRangeBonus.s

# target to generate assembly for a file
src/Game/Entities/Bonus/ResetFireRangeBonus.cpp.s:
	$(MAKE) -f CMakeFiles/bomberman.dir/build.make CMakeFiles/bomberman.dir/src/Game/Entities/Bonus/ResetFireRangeBonus.cpp.s
.PHONY : src/Game/Entities/Bonus/ResetFireRangeBonus.cpp.s

src/Game/Entities/Bonus/UpBombBonus.o: src/Game/Entities/Bonus/UpBombBonus.cpp.o

.PHONY : src/Game/Entities/Bonus/UpBombBonus.o

# target to build an object file
src/Game/Entities/Bonus/UpBombBonus.cpp.o:
	$(MAKE) -f CMakeFiles/bomberman.dir/build.make CMakeFiles/bomberman.dir/src/Game/Entities/Bonus/UpBombBonus.cpp.o
.PHONY : src/Game/Entities/Bonus/UpBombBonus.cpp.o

src/Game/Entities/Bonus/UpBombBonus.i: src/Game/Entities/Bonus/UpBombBonus.cpp.i

.PHONY : src/Game/Entities/Bonus/UpBombBonus.i

# target to preprocess a source file
src/Game/Entities/Bonus/UpBombBonus.cpp.i:
	$(MAKE) -f CMakeFiles/bomberman.dir/build.make CMakeFiles/bomberman.dir/src/Game/Entities/Bonus/UpBombBonus.cpp.i
.PHONY : src/Game/Entities/Bonus/UpBombBonus.cpp.i

src/Game/Entities/Bonus/UpBombBonus.s: src/Game/Entities/Bonus/UpBombBonus.cpp.s

.PHONY : src/Game/Entities/Bonus/UpBombBonus.s

# target to generate assembly for a file
src/Game/Entities/Bonus/UpBombBonus.cpp.s:
	$(MAKE) -f CMakeFiles/bomberman.dir/build.make CMakeFiles/bomberman.dir/src/Game/Entities/Bonus/UpBombBonus.cpp.s
.PHONY : src/Game/Entities/Bonus/UpBombBonus.cpp.s

src/Game/Entities/Bonus/UpFireBonus.o: src/Game/Entities/Bonus/UpFireBonus.cpp.o

.PHONY : src/Game/Entities/Bonus/UpFireBonus.o

# target to build an object file
src/Game/Entities/Bonus/UpFireBonus.cpp.o:
	$(MAKE) -f CMakeFiles/bomberman.dir/build.make CMakeFiles/bomberman.dir/src/Game/Entities/Bonus/UpFireBonus.cpp.o
.PHONY : src/Game/Entities/Bonus/UpFireBonus.cpp.o

src/Game/Entities/Bonus/UpFireBonus.i: src/Game/Entities/Bonus/UpFireBonus.cpp.i

.PHONY : src/Game/Entities/Bonus/UpFireBonus.i

# target to preprocess a source file
src/Game/Entities/Bonus/UpFireBonus.cpp.i:
	$(MAKE) -f CMakeFiles/bomberman.dir/build.make CMakeFiles/bomberman.dir/src/Game/Entities/Bonus/UpFireBonus.cpp.i
.PHONY : src/Game/Entities/Bonus/UpFireBonus.cpp.i

src/Game/Entities/Bonus/UpFireBonus.s: src/Game/Entities/Bonus/UpFireBonus.cpp.s

.PHONY : src/Game/Entities/Bonus/UpFireBonus.s

# target to generate assembly for a file
src/Game/Entities/Bonus/UpFireBonus.cpp.s:
	$(MAKE) -f CMakeFiles/bomberman.dir/build.make CMakeFiles/bomberman.dir/src/Game/Entities/Bonus/UpFireBonus.cpp.s
.PHONY : src/Game/Entities/Bonus/UpFireBonus.cpp.s

src/Game/Entities/FireEntity.o: src/Game/Entities/FireEntity.cpp.o

.PHONY : src/Game/Entities/FireEntity.o

# target to build an object file
src/Game/Entities/FireEntity.cpp.o:
	$(MAKE) -f CMakeFiles/bomberman.dir/build.make CMakeFiles/bomberman.dir/src/Game/Entities/FireEntity.cpp.o
.PHONY : src/Game/Entities/FireEntity.cpp.o

src/Game/Entities/FireEntity.i: src/Game/Entities/FireEntity.cpp.i

.PHONY : src/Game/Entities/FireEntity.i

# target to preprocess a source file
src/Game/Entities/FireEntity.cpp.i:
	$(MAKE) -f CMakeFiles/bomberman.dir/build.make CMakeFiles/bomberman.dir/src/Game/Entities/FireEntity.cpp.i
.PHONY : src/Game/Entities/FireEntity.cpp.i

src/Game/Entities/FireEntity.s: src/Game/Entities/FireEntity.cpp.s

.PHONY : src/Game/Entities/FireEntity.s

# target to generate assembly for a file
src/Game/Entities/FireEntity.cpp.s:
	$(MAKE) -f CMakeFiles/bomberman.dir/build.make CMakeFiles/bomberman.dir/src/Game/Entities/FireEntity.cpp.s
.PHONY : src/Game/Entities/FireEntity.cpp.s

src/Game/Entities/PlayerEntity.o: src/Game/Entities/PlayerEntity.cpp.o

.PHONY : src/Game/Entities/PlayerEntity.o

# target to build an object file
src/Game/Entities/PlayerEntity.cpp.o:
	$(MAKE) -f CMakeFiles/bomberman.dir/build.make CMakeFiles/bomberman.dir/src/Game/Entities/PlayerEntity.cpp.o
.PHONY : src/Game/Entities/PlayerEntity.cpp.o

src/Game/Entities/PlayerEntity.i: src/Game/Entities/PlayerEntity.cpp.i

.PHONY : src/Game/Entities/PlayerEntity.i

# target to preprocess a source file
src/Game/Entities/PlayerEntity.cpp.i:
	$(MAKE) -f CMakeFiles/bomberman.dir/build.make CMakeFiles/bomberman.dir/src/Game/Entities/PlayerEntity.cpp.i
.PHONY : src/Game/Entities/PlayerEntity.cpp.i

src/Game/Entities/PlayerEntity.s: src/Game/Entities/PlayerEntity.cpp.s

.PHONY : src/Game/Entities/PlayerEntity.s

# target to generate assembly for a file
src/Game/Entities/PlayerEntity.cpp.s:
	$(MAKE) -f CMakeFiles/bomberman.dir/build.make CMakeFiles/bomberman.dir/src/Game/Entities/PlayerEntity.cpp.s
.PHONY : src/Game/Entities/PlayerEntity.cpp.s

src/Game/Entities/PotEntity.o: src/Game/Entities/PotEntity.cpp.o

.PHONY : src/Game/Entities/PotEntity.o

# target to build an object file
src/Game/Entities/PotEntity.cpp.o:
	$(MAKE) -f CMakeFiles/bomberman.dir/build.make CMakeFiles/bomberman.dir/src/Game/Entities/PotEntity.cpp.o
.PHONY : src/Game/Entities/PotEntity.cpp.o

src/Game/Entities/PotEntity.i: src/Game/Entities/PotEntity.cpp.i

.PHONY : src/Game/Entities/PotEntity.i

# target to preprocess a source file
src/Game/Entities/PotEntity.cpp.i:
	$(MAKE) -f CMakeFiles/bomberman.dir/build.make CMakeFiles/bomberman.dir/src/Game/Entities/PotEntity.cpp.i
.PHONY : src/Game/Entities/PotEntity.cpp.i

src/Game/Entities/PotEntity.s: src/Game/Entities/PotEntity.cpp.s

.PHONY : src/Game/Entities/PotEntity.s

# target to generate assembly for a file
src/Game/Entities/PotEntity.cpp.s:
	$(MAKE) -f CMakeFiles/bomberman.dir/build.make CMakeFiles/bomberman.dir/src/Game/Entities/PotEntity.cpp.s
.PHONY : src/Game/Entities/PotEntity.cpp.s

src/Game/EntitiesMap.o: src/Game/EntitiesMap.cpp.o

.PHONY : src/Game/EntitiesMap.o

# target to build an object file
src/Game/EntitiesMap.cpp.o:
	$(MAKE) -f CMakeFiles/bomberman.dir/build.make CMakeFiles/bomberman.dir/src/Game/EntitiesMap.cpp.o
.PHONY : src/Game/EntitiesMap.cpp.o

src/Game/EntitiesMap.i: src/Game/EntitiesMap.cpp.i

.PHONY : src/Game/EntitiesMap.i

# target to preprocess a source file
src/Game/EntitiesMap.cpp.i:
	$(MAKE) -f CMakeFiles/bomberman.dir/build.make CMakeFiles/bomberman.dir/src/Game/EntitiesMap.cpp.i
.PHONY : src/Game/EntitiesMap.cpp.i

src/Game/EntitiesMap.s: src/Game/EntitiesMap.cpp.s

.PHONY : src/Game/EntitiesMap.s

# target to generate assembly for a file
src/Game/EntitiesMap.cpp.s:
	$(MAKE) -f CMakeFiles/bomberman.dir/build.make CMakeFiles/bomberman.dir/src/Game/EntitiesMap.cpp.s
.PHONY : src/Game/EntitiesMap.cpp.s

src/Game/EntityFactory.o: src/Game/EntityFactory.cpp.o

.PHONY : src/Game/EntityFactory.o

# target to build an object file
src/Game/EntityFactory.cpp.o:
	$(MAKE) -f CMakeFiles/bomberman.dir/build.make CMakeFiles/bomberman.dir/src/Game/EntityFactory.cpp.o
.PHONY : src/Game/EntityFactory.cpp.o

src/Game/EntityFactory.i: src/Game/EntityFactory.cpp.i

.PHONY : src/Game/EntityFactory.i

# target to preprocess a source file
src/Game/EntityFactory.cpp.i:
	$(MAKE) -f CMakeFiles/bomberman.dir/build.make CMakeFiles/bomberman.dir/src/Game/EntityFactory.cpp.i
.PHONY : src/Game/EntityFactory.cpp.i

src/Game/EntityFactory.s: src/Game/EntityFactory.cpp.s

.PHONY : src/Game/EntityFactory.s

# target to generate assembly for a file
src/Game/EntityFactory.cpp.s:
	$(MAKE) -f CMakeFiles/bomberman.dir/build.make CMakeFiles/bomberman.dir/src/Game/EntityFactory.cpp.s
.PHONY : src/Game/EntityFactory.cpp.s

src/Game/SaveManager.o: src/Game/SaveManager.cpp.o

.PHONY : src/Game/SaveManager.o

# target to build an object file
src/Game/SaveManager.cpp.o:
	$(MAKE) -f CMakeFiles/bomberman.dir/build.make CMakeFiles/bomberman.dir/src/Game/SaveManager.cpp.o
.PHONY : src/Game/SaveManager.cpp.o

src/Game/SaveManager.i: src/Game/SaveManager.cpp.i

.PHONY : src/Game/SaveManager.i

# target to preprocess a source file
src/Game/SaveManager.cpp.i:
	$(MAKE) -f CMakeFiles/bomberman.dir/build.make CMakeFiles/bomberman.dir/src/Game/SaveManager.cpp.i
.PHONY : src/Game/SaveManager.cpp.i

src/Game/SaveManager.s: src/Game/SaveManager.cpp.s

.PHONY : src/Game/SaveManager.s

# target to generate assembly for a file
src/Game/SaveManager.cpp.s:
	$(MAKE) -f CMakeFiles/bomberman.dir/build.make CMakeFiles/bomberman.dir/src/Game/SaveManager.cpp.s
.PHONY : src/Game/SaveManager.cpp.s

src/Game/SphericalCoordinate.o: src/Game/SphericalCoordinate.cpp.o

.PHONY : src/Game/SphericalCoordinate.o

# target to build an object file
src/Game/SphericalCoordinate.cpp.o:
	$(MAKE) -f CMakeFiles/bomberman.dir/build.make CMakeFiles/bomberman.dir/src/Game/SphericalCoordinate.cpp.o
.PHONY : src/Game/SphericalCoordinate.cpp.o

src/Game/SphericalCoordinate.i: src/Game/SphericalCoordinate.cpp.i

.PHONY : src/Game/SphericalCoordinate.i

# target to preprocess a source file
src/Game/SphericalCoordinate.cpp.i:
	$(MAKE) -f CMakeFiles/bomberman.dir/build.make CMakeFiles/bomberman.dir/src/Game/SphericalCoordinate.cpp.i
.PHONY : src/Game/SphericalCoordinate.cpp.i

src/Game/SphericalCoordinate.s: src/Game/SphericalCoordinate.cpp.s

.PHONY : src/Game/SphericalCoordinate.s

# target to generate assembly for a file
src/Game/SphericalCoordinate.cpp.s:
	$(MAKE) -f CMakeFiles/bomberman.dir/build.make CMakeFiles/bomberman.dir/src/Game/SphericalCoordinate.cpp.s
.PHONY : src/Game/SphericalCoordinate.cpp.s

src/Game/Traveling.o: src/Game/Traveling.cpp.o

.PHONY : src/Game/Traveling.o

# target to build an object file
src/Game/Traveling.cpp.o:
	$(MAKE) -f CMakeFiles/bomberman.dir/build.make CMakeFiles/bomberman.dir/src/Game/Traveling.cpp.o
.PHONY : src/Game/Traveling.cpp.o

src/Game/Traveling.i: src/Game/Traveling.cpp.i

.PHONY : src/Game/Traveling.i

# target to preprocess a source file
src/Game/Traveling.cpp.i:
	$(MAKE) -f CMakeFiles/bomberman.dir/build.make CMakeFiles/bomberman.dir/src/Game/Traveling.cpp.i
.PHONY : src/Game/Traveling.cpp.i

src/Game/Traveling.s: src/Game/Traveling.cpp.s

.PHONY : src/Game/Traveling.s

# target to generate assembly for a file
src/Game/Traveling.cpp.s:
	$(MAKE) -f CMakeFiles/bomberman.dir/build.make CMakeFiles/bomberman.dir/src/Game/Traveling.cpp.s
.PHONY : src/Game/Traveling.cpp.s

src/Singletons/AssetsPool.o: src/Singletons/AssetsPool.cpp.o

.PHONY : src/Singletons/AssetsPool.o

# target to build an object file
src/Singletons/AssetsPool.cpp.o:
	$(MAKE) -f CMakeFiles/bomberman.dir/build.make CMakeFiles/bomberman.dir/src/Singletons/AssetsPool.cpp.o
.PHONY : src/Singletons/AssetsPool.cpp.o

src/Singletons/AssetsPool.i: src/Singletons/AssetsPool.cpp.i

.PHONY : src/Singletons/AssetsPool.i

# target to preprocess a source file
src/Singletons/AssetsPool.cpp.i:
	$(MAKE) -f CMakeFiles/bomberman.dir/build.make CMakeFiles/bomberman.dir/src/Singletons/AssetsPool.cpp.i
.PHONY : src/Singletons/AssetsPool.cpp.i

src/Singletons/AssetsPool.s: src/Singletons/AssetsPool.cpp.s

.PHONY : src/Singletons/AssetsPool.s

# target to generate assembly for a file
src/Singletons/AssetsPool.cpp.s:
	$(MAKE) -f CMakeFiles/bomberman.dir/build.make CMakeFiles/bomberman.dir/src/Singletons/AssetsPool.cpp.s
.PHONY : src/Singletons/AssetsPool.cpp.s

src/Singletons/EventReceiver.o: src/Singletons/EventReceiver.cpp.o

.PHONY : src/Singletons/EventReceiver.o

# target to build an object file
src/Singletons/EventReceiver.cpp.o:
	$(MAKE) -f CMakeFiles/bomberman.dir/build.make CMakeFiles/bomberman.dir/src/Singletons/EventReceiver.cpp.o
.PHONY : src/Singletons/EventReceiver.cpp.o

src/Singletons/EventReceiver.i: src/Singletons/EventReceiver.cpp.i

.PHONY : src/Singletons/EventReceiver.i

# target to preprocess a source file
src/Singletons/EventReceiver.cpp.i:
	$(MAKE) -f CMakeFiles/bomberman.dir/build.make CMakeFiles/bomberman.dir/src/Singletons/EventReceiver.cpp.i
.PHONY : src/Singletons/EventReceiver.cpp.i

src/Singletons/EventReceiver.s: src/Singletons/EventReceiver.cpp.s

.PHONY : src/Singletons/EventReceiver.s

# target to generate assembly for a file
src/Singletons/EventReceiver.cpp.s:
	$(MAKE) -f CMakeFiles/bomberman.dir/build.make CMakeFiles/bomberman.dir/src/Singletons/EventReceiver.cpp.s
.PHONY : src/Singletons/EventReceiver.cpp.s

src/Singletons/IrrManager.o: src/Singletons/IrrManager.cpp.o

.PHONY : src/Singletons/IrrManager.o

# target to build an object file
src/Singletons/IrrManager.cpp.o:
	$(MAKE) -f CMakeFiles/bomberman.dir/build.make CMakeFiles/bomberman.dir/src/Singletons/IrrManager.cpp.o
.PHONY : src/Singletons/IrrManager.cpp.o

src/Singletons/IrrManager.i: src/Singletons/IrrManager.cpp.i

.PHONY : src/Singletons/IrrManager.i

# target to preprocess a source file
src/Singletons/IrrManager.cpp.i:
	$(MAKE) -f CMakeFiles/bomberman.dir/build.make CMakeFiles/bomberman.dir/src/Singletons/IrrManager.cpp.i
.PHONY : src/Singletons/IrrManager.cpp.i

src/Singletons/IrrManager.s: src/Singletons/IrrManager.cpp.s

.PHONY : src/Singletons/IrrManager.s

# target to generate assembly for a file
src/Singletons/IrrManager.cpp.s:
	$(MAKE) -f CMakeFiles/bomberman.dir/build.make CMakeFiles/bomberman.dir/src/Singletons/IrrManager.cpp.s
.PHONY : src/Singletons/IrrManager.cpp.s

src/Singletons/StateMachine.o: src/Singletons/StateMachine.cpp.o

.PHONY : src/Singletons/StateMachine.o

# target to build an object file
src/Singletons/StateMachine.cpp.o:
	$(MAKE) -f CMakeFiles/bomberman.dir/build.make CMakeFiles/bomberman.dir/src/Singletons/StateMachine.cpp.o
.PHONY : src/Singletons/StateMachine.cpp.o

src/Singletons/StateMachine.i: src/Singletons/StateMachine.cpp.i

.PHONY : src/Singletons/StateMachine.i

# target to preprocess a source file
src/Singletons/StateMachine.cpp.i:
	$(MAKE) -f CMakeFiles/bomberman.dir/build.make CMakeFiles/bomberman.dir/src/Singletons/StateMachine.cpp.i
.PHONY : src/Singletons/StateMachine.cpp.i

src/Singletons/StateMachine.s: src/Singletons/StateMachine.cpp.s

.PHONY : src/Singletons/StateMachine.s

# target to generate assembly for a file
src/Singletons/StateMachine.cpp.s:
	$(MAKE) -f CMakeFiles/bomberman.dir/build.make CMakeFiles/bomberman.dir/src/Singletons/StateMachine.cpp.s
.PHONY : src/Singletons/StateMachine.cpp.s

src/States/AIChooseState.o: src/States/AIChooseState.cpp.o

.PHONY : src/States/AIChooseState.o

# target to build an object file
src/States/AIChooseState.cpp.o:
	$(MAKE) -f CMakeFiles/bomberman.dir/build.make CMakeFiles/bomberman.dir/src/States/AIChooseState.cpp.o
.PHONY : src/States/AIChooseState.cpp.o

src/States/AIChooseState.i: src/States/AIChooseState.cpp.i

.PHONY : src/States/AIChooseState.i

# target to preprocess a source file
src/States/AIChooseState.cpp.i:
	$(MAKE) -f CMakeFiles/bomberman.dir/build.make CMakeFiles/bomberman.dir/src/States/AIChooseState.cpp.i
.PHONY : src/States/AIChooseState.cpp.i

src/States/AIChooseState.s: src/States/AIChooseState.cpp.s

.PHONY : src/States/AIChooseState.s

# target to generate assembly for a file
src/States/AIChooseState.cpp.s:
	$(MAKE) -f CMakeFiles/bomberman.dir/build.make CMakeFiles/bomberman.dir/src/States/AIChooseState.cpp.s
.PHONY : src/States/AIChooseState.cpp.s

src/States/BackgroundState.o: src/States/BackgroundState.cpp.o

.PHONY : src/States/BackgroundState.o

# target to build an object file
src/States/BackgroundState.cpp.o:
	$(MAKE) -f CMakeFiles/bomberman.dir/build.make CMakeFiles/bomberman.dir/src/States/BackgroundState.cpp.o
.PHONY : src/States/BackgroundState.cpp.o

src/States/BackgroundState.i: src/States/BackgroundState.cpp.i

.PHONY : src/States/BackgroundState.i

# target to preprocess a source file
src/States/BackgroundState.cpp.i:
	$(MAKE) -f CMakeFiles/bomberman.dir/build.make CMakeFiles/bomberman.dir/src/States/BackgroundState.cpp.i
.PHONY : src/States/BackgroundState.cpp.i

src/States/BackgroundState.s: src/States/BackgroundState.cpp.s

.PHONY : src/States/BackgroundState.s

# target to generate assembly for a file
src/States/BackgroundState.cpp.s:
	$(MAKE) -f CMakeFiles/bomberman.dir/build.make CMakeFiles/bomberman.dir/src/States/BackgroundState.cpp.s
.PHONY : src/States/BackgroundState.cpp.s

src/States/EndGameState.o: src/States/EndGameState.cpp.o

.PHONY : src/States/EndGameState.o

# target to build an object file
src/States/EndGameState.cpp.o:
	$(MAKE) -f CMakeFiles/bomberman.dir/build.make CMakeFiles/bomberman.dir/src/States/EndGameState.cpp.o
.PHONY : src/States/EndGameState.cpp.o

src/States/EndGameState.i: src/States/EndGameState.cpp.i

.PHONY : src/States/EndGameState.i

# target to preprocess a source file
src/States/EndGameState.cpp.i:
	$(MAKE) -f CMakeFiles/bomberman.dir/build.make CMakeFiles/bomberman.dir/src/States/EndGameState.cpp.i
.PHONY : src/States/EndGameState.cpp.i

src/States/EndGameState.s: src/States/EndGameState.cpp.s

.PHONY : src/States/EndGameState.s

# target to generate assembly for a file
src/States/EndGameState.cpp.s:
	$(MAKE) -f CMakeFiles/bomberman.dir/build.make CMakeFiles/bomberman.dir/src/States/EndGameState.cpp.s
.PHONY : src/States/EndGameState.cpp.s

src/States/GameState.o: src/States/GameState.cpp.o

.PHONY : src/States/GameState.o

# target to build an object file
src/States/GameState.cpp.o:
	$(MAKE) -f CMakeFiles/bomberman.dir/build.make CMakeFiles/bomberman.dir/src/States/GameState.cpp.o
.PHONY : src/States/GameState.cpp.o

src/States/GameState.i: src/States/GameState.cpp.i

.PHONY : src/States/GameState.i

# target to preprocess a source file
src/States/GameState.cpp.i:
	$(MAKE) -f CMakeFiles/bomberman.dir/build.make CMakeFiles/bomberman.dir/src/States/GameState.cpp.i
.PHONY : src/States/GameState.cpp.i

src/States/GameState.s: src/States/GameState.cpp.s

.PHONY : src/States/GameState.s

# target to generate assembly for a file
src/States/GameState.cpp.s:
	$(MAKE) -f CMakeFiles/bomberman.dir/build.make CMakeFiles/bomberman.dir/src/States/GameState.cpp.s
.PHONY : src/States/GameState.cpp.s

src/States/LoadState.o: src/States/LoadState.cpp.o

.PHONY : src/States/LoadState.o

# target to build an object file
src/States/LoadState.cpp.o:
	$(MAKE) -f CMakeFiles/bomberman.dir/build.make CMakeFiles/bomberman.dir/src/States/LoadState.cpp.o
.PHONY : src/States/LoadState.cpp.o

src/States/LoadState.i: src/States/LoadState.cpp.i

.PHONY : src/States/LoadState.i

# target to preprocess a source file
src/States/LoadState.cpp.i:
	$(MAKE) -f CMakeFiles/bomberman.dir/build.make CMakeFiles/bomberman.dir/src/States/LoadState.cpp.i
.PHONY : src/States/LoadState.cpp.i

src/States/LoadState.s: src/States/LoadState.cpp.s

.PHONY : src/States/LoadState.s

# target to generate assembly for a file
src/States/LoadState.cpp.s:
	$(MAKE) -f CMakeFiles/bomberman.dir/build.make CMakeFiles/bomberman.dir/src/States/LoadState.cpp.s
.PHONY : src/States/LoadState.cpp.s

src/States/MenuState.o: src/States/MenuState.cpp.o

.PHONY : src/States/MenuState.o

# target to build an object file
src/States/MenuState.cpp.o:
	$(MAKE) -f CMakeFiles/bomberman.dir/build.make CMakeFiles/bomberman.dir/src/States/MenuState.cpp.o
.PHONY : src/States/MenuState.cpp.o

src/States/MenuState.i: src/States/MenuState.cpp.i

.PHONY : src/States/MenuState.i

# target to preprocess a source file
src/States/MenuState.cpp.i:
	$(MAKE) -f CMakeFiles/bomberman.dir/build.make CMakeFiles/bomberman.dir/src/States/MenuState.cpp.i
.PHONY : src/States/MenuState.cpp.i

src/States/MenuState.s: src/States/MenuState.cpp.s

.PHONY : src/States/MenuState.s

# target to generate assembly for a file
src/States/MenuState.cpp.s:
	$(MAKE) -f CMakeFiles/bomberman.dir/build.make CMakeFiles/bomberman.dir/src/States/MenuState.cpp.s
.PHONY : src/States/MenuState.cpp.s

src/States/PauseState.o: src/States/PauseState.cpp.o

.PHONY : src/States/PauseState.o

# target to build an object file
src/States/PauseState.cpp.o:
	$(MAKE) -f CMakeFiles/bomberman.dir/build.make CMakeFiles/bomberman.dir/src/States/PauseState.cpp.o
.PHONY : src/States/PauseState.cpp.o

src/States/PauseState.i: src/States/PauseState.cpp.i

.PHONY : src/States/PauseState.i

# target to preprocess a source file
src/States/PauseState.cpp.i:
	$(MAKE) -f CMakeFiles/bomberman.dir/build.make CMakeFiles/bomberman.dir/src/States/PauseState.cpp.i
.PHONY : src/States/PauseState.cpp.i

src/States/PauseState.s: src/States/PauseState.cpp.s

.PHONY : src/States/PauseState.s

# target to generate assembly for a file
src/States/PauseState.cpp.s:
	$(MAKE) -f CMakeFiles/bomberman.dir/build.make CMakeFiles/bomberman.dir/src/States/PauseState.cpp.s
.PHONY : src/States/PauseState.cpp.s

src/States/SaveState.o: src/States/SaveState.cpp.o

.PHONY : src/States/SaveState.o

# target to build an object file
src/States/SaveState.cpp.o:
	$(MAKE) -f CMakeFiles/bomberman.dir/build.make CMakeFiles/bomberman.dir/src/States/SaveState.cpp.o
.PHONY : src/States/SaveState.cpp.o

src/States/SaveState.i: src/States/SaveState.cpp.i

.PHONY : src/States/SaveState.i

# target to preprocess a source file
src/States/SaveState.cpp.i:
	$(MAKE) -f CMakeFiles/bomberman.dir/build.make CMakeFiles/bomberman.dir/src/States/SaveState.cpp.i
.PHONY : src/States/SaveState.cpp.i

src/States/SaveState.s: src/States/SaveState.cpp.s

.PHONY : src/States/SaveState.s

# target to generate assembly for a file
src/States/SaveState.cpp.s:
	$(MAKE) -f CMakeFiles/bomberman.dir/build.make CMakeFiles/bomberman.dir/src/States/SaveState.cpp.s
.PHONY : src/States/SaveState.cpp.s

src/States/SettingsState.o: src/States/SettingsState.cpp.o

.PHONY : src/States/SettingsState.o

# target to build an object file
src/States/SettingsState.cpp.o:
	$(MAKE) -f CMakeFiles/bomberman.dir/build.make CMakeFiles/bomberman.dir/src/States/SettingsState.cpp.o
.PHONY : src/States/SettingsState.cpp.o

src/States/SettingsState.i: src/States/SettingsState.cpp.i

.PHONY : src/States/SettingsState.i

# target to preprocess a source file
src/States/SettingsState.cpp.i:
	$(MAKE) -f CMakeFiles/bomberman.dir/build.make CMakeFiles/bomberman.dir/src/States/SettingsState.cpp.i
.PHONY : src/States/SettingsState.cpp.i

src/States/SettingsState.s: src/States/SettingsState.cpp.s

.PHONY : src/States/SettingsState.s

# target to generate assembly for a file
src/States/SettingsState.cpp.s:
	$(MAKE) -f CMakeFiles/bomberman.dir/build.make CMakeFiles/bomberman.dir/src/States/SettingsState.cpp.s
.PHONY : src/States/SettingsState.cpp.s

src/States/SplashState.o: src/States/SplashState.cpp.o

.PHONY : src/States/SplashState.o

# target to build an object file
src/States/SplashState.cpp.o:
	$(MAKE) -f CMakeFiles/bomberman.dir/build.make CMakeFiles/bomberman.dir/src/States/SplashState.cpp.o
.PHONY : src/States/SplashState.cpp.o

src/States/SplashState.i: src/States/SplashState.cpp.i

.PHONY : src/States/SplashState.i

# target to preprocess a source file
src/States/SplashState.cpp.i:
	$(MAKE) -f CMakeFiles/bomberman.dir/build.make CMakeFiles/bomberman.dir/src/States/SplashState.cpp.i
.PHONY : src/States/SplashState.cpp.i

src/States/SplashState.s: src/States/SplashState.cpp.s

.PHONY : src/States/SplashState.s

# target to generate assembly for a file
src/States/SplashState.cpp.s:
	$(MAKE) -f CMakeFiles/bomberman.dir/build.make CMakeFiles/bomberman.dir/src/States/SplashState.cpp.s
.PHONY : src/States/SplashState.cpp.s

src/States/TransitionEndGameState.o: src/States/TransitionEndGameState.cpp.o

.PHONY : src/States/TransitionEndGameState.o

# target to build an object file
src/States/TransitionEndGameState.cpp.o:
	$(MAKE) -f CMakeFiles/bomberman.dir/build.make CMakeFiles/bomberman.dir/src/States/TransitionEndGameState.cpp.o
.PHONY : src/States/TransitionEndGameState.cpp.o

src/States/TransitionEndGameState.i: src/States/TransitionEndGameState.cpp.i

.PHONY : src/States/TransitionEndGameState.i

# target to preprocess a source file
src/States/TransitionEndGameState.cpp.i:
	$(MAKE) -f CMakeFiles/bomberman.dir/build.make CMakeFiles/bomberman.dir/src/States/TransitionEndGameState.cpp.i
.PHONY : src/States/TransitionEndGameState.cpp.i

src/States/TransitionEndGameState.s: src/States/TransitionEndGameState.cpp.s

.PHONY : src/States/TransitionEndGameState.s

# target to generate assembly for a file
src/States/TransitionEndGameState.cpp.s:
	$(MAKE) -f CMakeFiles/bomberman.dir/build.make CMakeFiles/bomberman.dir/src/States/TransitionEndGameState.cpp.s
.PHONY : src/States/TransitionEndGameState.cpp.s

src/States/TransitionToGameState.o: src/States/TransitionToGameState.cpp.o

.PHONY : src/States/TransitionToGameState.o

# target to build an object file
src/States/TransitionToGameState.cpp.o:
	$(MAKE) -f CMakeFiles/bomberman.dir/build.make CMakeFiles/bomberman.dir/src/States/TransitionToGameState.cpp.o
.PHONY : src/States/TransitionToGameState.cpp.o

src/States/TransitionToGameState.i: src/States/TransitionToGameState.cpp.i

.PHONY : src/States/TransitionToGameState.i

# target to preprocess a source file
src/States/TransitionToGameState.cpp.i:
	$(MAKE) -f CMakeFiles/bomberman.dir/build.make CMakeFiles/bomberman.dir/src/States/TransitionToGameState.cpp.i
.PHONY : src/States/TransitionToGameState.cpp.i

src/States/TransitionToGameState.s: src/States/TransitionToGameState.cpp.s

.PHONY : src/States/TransitionToGameState.s

# target to generate assembly for a file
src/States/TransitionToGameState.cpp.s:
	$(MAKE) -f CMakeFiles/bomberman.dir/build.make CMakeFiles/bomberman.dir/src/States/TransitionToGameState.cpp.s
.PHONY : src/States/TransitionToGameState.cpp.s

src/Time.o: src/Time.cpp.o

.PHONY : src/Time.o

# target to build an object file
src/Time.cpp.o:
	$(MAKE) -f CMakeFiles/bomberman.dir/build.make CMakeFiles/bomberman.dir/src/Time.cpp.o
.PHONY : src/Time.cpp.o

src/Time.i: src/Time.cpp.i

.PHONY : src/Time.i

# target to preprocess a source file
src/Time.cpp.i:
	$(MAKE) -f CMakeFiles/bomberman.dir/build.make CMakeFiles/bomberman.dir/src/Time.cpp.i
.PHONY : src/Time.cpp.i

src/Time.s: src/Time.cpp.s

.PHONY : src/Time.s

# target to generate assembly for a file
src/Time.cpp.s:
	$(MAKE) -f CMakeFiles/bomberman.dir/build.make CMakeFiles/bomberman.dir/src/Time.cpp.s
.PHONY : src/Time.cpp.s

src/main.o: src/main.cpp.o

.PHONY : src/main.o

# target to build an object file
src/main.cpp.o:
	$(MAKE) -f CMakeFiles/bomberman.dir/build.make CMakeFiles/bomberman.dir/src/main.cpp.o
.PHONY : src/main.cpp.o

src/main.i: src/main.cpp.i

.PHONY : src/main.i

# target to preprocess a source file
src/main.cpp.i:
	$(MAKE) -f CMakeFiles/bomberman.dir/build.make CMakeFiles/bomberman.dir/src/main.cpp.i
.PHONY : src/main.cpp.i

src/main.s: src/main.cpp.s

.PHONY : src/main.s

# target to generate assembly for a file
src/main.cpp.s:
	$(MAKE) -f CMakeFiles/bomberman.dir/build.make CMakeFiles/bomberman.dir/src/main.cpp.s
.PHONY : src/main.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... rebuild_cache"
	@echo "... edit_cache"
	@echo "... bomberman"
	@echo "... src/Abstracts/ABombDropper.o"
	@echo "... src/Abstracts/ABombDropper.i"
	@echo "... src/Abstracts/ABombDropper.s"
	@echo "... src/Abstracts/AMenuSound.o"
	@echo "... src/Abstracts/AMenuSound.i"
	@echo "... src/Abstracts/AMenuSound.s"
	@echo "... src/Abstracts/AState.o"
	@echo "... src/Abstracts/AState.i"
	@echo "... src/Abstracts/AState.s"
	@echo "... src/Abstracts/AStateShare.o"
	@echo "... src/Abstracts/AStateShare.i"
	@echo "... src/Abstracts/AStateShare.s"
	@echo "... src/Game/AController.o"
	@echo "... src/Game/AController.i"
	@echo "... src/Game/AController.s"
	@echo "... src/Game/AEntity.o"
	@echo "... src/Game/AEntity.i"
	@echo "... src/Game/AEntity.s"
	@echo "... src/Game/BIAController.o"
	@echo "... src/Game/BIAController.i"
	@echo "... src/Game/BIAController.s"
	@echo "... src/Game/BKeyboardController.o"
	@echo "... src/Game/BKeyboardController.i"
	@echo "... src/Game/BKeyboardController.s"
	@echo "... src/Game/Controllable.o"
	@echo "... src/Game/Controllable.i"
	@echo "... src/Game/Controllable.s"
	@echo "... src/Game/Entities/AAnimatedEntity.o"
	@echo "... src/Game/Entities/AAnimatedEntity.i"
	@echo "... src/Game/Entities/AAnimatedEntity.s"
	@echo "... src/Game/Entities/ABonusEntity.o"
	@echo "... src/Game/Entities/ABonusEntity.i"
	@echo "... src/Game/Entities/ABonusEntity.s"
	@echo "... src/Game/Entities/BlockEntity.o"
	@echo "... src/Game/Entities/BlockEntity.i"
	@echo "... src/Game/Entities/BlockEntity.s"
	@echo "... src/Game/Entities/BombEntity.o"
	@echo "... src/Game/Entities/BombEntity.i"
	@echo "... src/Game/Entities/BombEntity.s"
	@echo "... src/Game/Entities/Bonus/InvertBonus.o"
	@echo "... src/Game/Entities/Bonus/InvertBonus.i"
	@echo "... src/Game/Entities/Bonus/InvertBonus.s"
	@echo "... src/Game/Entities/Bonus/ResetFireRangeBonus.o"
	@echo "... src/Game/Entities/Bonus/ResetFireRangeBonus.i"
	@echo "... src/Game/Entities/Bonus/ResetFireRangeBonus.s"
	@echo "... src/Game/Entities/Bonus/UpBombBonus.o"
	@echo "... src/Game/Entities/Bonus/UpBombBonus.i"
	@echo "... src/Game/Entities/Bonus/UpBombBonus.s"
	@echo "... src/Game/Entities/Bonus/UpFireBonus.o"
	@echo "... src/Game/Entities/Bonus/UpFireBonus.i"
	@echo "... src/Game/Entities/Bonus/UpFireBonus.s"
	@echo "... src/Game/Entities/FireEntity.o"
	@echo "... src/Game/Entities/FireEntity.i"
	@echo "... src/Game/Entities/FireEntity.s"
	@echo "... src/Game/Entities/PlayerEntity.o"
	@echo "... src/Game/Entities/PlayerEntity.i"
	@echo "... src/Game/Entities/PlayerEntity.s"
	@echo "... src/Game/Entities/PotEntity.o"
	@echo "... src/Game/Entities/PotEntity.i"
	@echo "... src/Game/Entities/PotEntity.s"
	@echo "... src/Game/EntitiesMap.o"
	@echo "... src/Game/EntitiesMap.i"
	@echo "... src/Game/EntitiesMap.s"
	@echo "... src/Game/EntityFactory.o"
	@echo "... src/Game/EntityFactory.i"
	@echo "... src/Game/EntityFactory.s"
	@echo "... src/Game/SaveManager.o"
	@echo "... src/Game/SaveManager.i"
	@echo "... src/Game/SaveManager.s"
	@echo "... src/Game/SphericalCoordinate.o"
	@echo "... src/Game/SphericalCoordinate.i"
	@echo "... src/Game/SphericalCoordinate.s"
	@echo "... src/Game/Traveling.o"
	@echo "... src/Game/Traveling.i"
	@echo "... src/Game/Traveling.s"
	@echo "... src/Singletons/AssetsPool.o"
	@echo "... src/Singletons/AssetsPool.i"
	@echo "... src/Singletons/AssetsPool.s"
	@echo "... src/Singletons/EventReceiver.o"
	@echo "... src/Singletons/EventReceiver.i"
	@echo "... src/Singletons/EventReceiver.s"
	@echo "... src/Singletons/IrrManager.o"
	@echo "... src/Singletons/IrrManager.i"
	@echo "... src/Singletons/IrrManager.s"
	@echo "... src/Singletons/StateMachine.o"
	@echo "... src/Singletons/StateMachine.i"
	@echo "... src/Singletons/StateMachine.s"
	@echo "... src/States/AIChooseState.o"
	@echo "... src/States/AIChooseState.i"
	@echo "... src/States/AIChooseState.s"
	@echo "... src/States/BackgroundState.o"
	@echo "... src/States/BackgroundState.i"
	@echo "... src/States/BackgroundState.s"
	@echo "... src/States/EndGameState.o"
	@echo "... src/States/EndGameState.i"
	@echo "... src/States/EndGameState.s"
	@echo "... src/States/GameState.o"
	@echo "... src/States/GameState.i"
	@echo "... src/States/GameState.s"
	@echo "... src/States/LoadState.o"
	@echo "... src/States/LoadState.i"
	@echo "... src/States/LoadState.s"
	@echo "... src/States/MenuState.o"
	@echo "... src/States/MenuState.i"
	@echo "... src/States/MenuState.s"
	@echo "... src/States/PauseState.o"
	@echo "... src/States/PauseState.i"
	@echo "... src/States/PauseState.s"
	@echo "... src/States/SaveState.o"
	@echo "... src/States/SaveState.i"
	@echo "... src/States/SaveState.s"
	@echo "... src/States/SettingsState.o"
	@echo "... src/States/SettingsState.i"
	@echo "... src/States/SettingsState.s"
	@echo "... src/States/SplashState.o"
	@echo "... src/States/SplashState.i"
	@echo "... src/States/SplashState.s"
	@echo "... src/States/TransitionEndGameState.o"
	@echo "... src/States/TransitionEndGameState.i"
	@echo "... src/States/TransitionEndGameState.s"
	@echo "... src/States/TransitionToGameState.o"
	@echo "... src/States/TransitionToGameState.i"
	@echo "... src/States/TransitionToGameState.s"
	@echo "... src/Time.o"
	@echo "... src/Time.i"
	@echo "... src/Time.s"
	@echo "... src/main.o"
	@echo "... src/main.i"
	@echo "... src/main.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

